name: Pack Emacs configurations with submodule downloaded
on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  TAG_NAME: latest

jobs:
  release:
    name: Pack Celeste Emacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update submodules
        run: |
          sed -i '/shallow = true/d' .gitmodules
          git submodule update --init --recursive

      - name: Create tarball
        run: |
          cd ..
          tar zcvf celeste-emacs-${{ env.TAG_NAME }}.tar.gz \
              --exclude=.git \
              --exclude=*.png \
              --exclude=*.gif \
              .emacs.d
          mv celeste-emacs-${{ env.TAG_NAME }}.tar.gz .emacs.d/

      - name: Generate SHA256 checksum
        run: |
          sha256sum celeste-emacs-* > SHA256SUMS.txt
          cat SHA256SUMS.txt

      - name: List files
        run: |
          ls -lh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          prerelease: true
          files: |
            celeste-emacs-${{ env.TAG_NAME }}.tar.gz
            SHA256SUMS.txt
          tag_name: ${{ env.TAG_NAME }}
